### PR TITLE
Add support for _NET_WM_PID

### PR DESCRIPTION
**Pull request by kdienes**

### CODE REVIEW

**Comment by kdienes** [comment]
Is there anything I can do to make this patch more useful?  I think it's relatively straightforward and improves freedesktop standards compliance.  But I'd be happy to modify it if there are any concerns.

**Comment by kdienes** [comment]
I've updated the patch to the latest top of tree.  Please let me know if there's anything that you dislike about the patch, or if there's anything I can do to make it more likely to be accepted.

**Comment by derf** [comment]
Hi,

Sorry, I completely missed this request. It looks fine, I just made two minor changes:

* It's sufficient to set the PID in winwidget_create_window, it doesn't need to be updated whenever winwidget_update_title is called (the code layout is a bit misleading there, I guess)
* According to the X11 spec one should also set WM_CLIENT_MACHINE whin setting _NET_WM_PID, so I added that

This feature will be included in the next release, thanks a lot!

**Comment by kdienes** [comment]
Thanks!  Sorry to have missed the part about WM_CLIENT_MACHINE.  Thanks for taking care of it and thanks for continuing to support feh!

**Pull request merged**
