### PR TITLE
Option Refactor and addition of Zoom Rate

### LINKED ISSUE #576: Req: specify zoom step
It would be awesome if users somehow could specify the zoom step. I'd love the ability for smoother zooming! If it was a commandline flag with some sort of value, then it could also be used in themes.

### PR DESCRIPTION
**Pull request by avlec**
Change adds --zoom-rate <ratio>, --zoom-in-rate <ratio>, and --zoom-out-rate <ratio>. These options allow the user to specify different ratios for alternatives to the programs 1.25 zoom in and 0.8 zoom out factor, but still keeps them as defaults.
During this change it was thought that it would be beneficial to improve program readability by replacing the abstract numerical values in the following two places. This change implements the use of an enum to improve option specification readability. This also improves the readability of the option handling switch.
https://github.com/derf/feh/blob/master/src/options.c#L332 (for lopts defintions)
https://github.com/derf/feh/blob/master/src/options.c#L687 (and onward)

Reviews to make sure that any of the changes made don't impair program functionality. But from my testing it seems to work with no immediately obvious problems.

resolves #576

### CODE REVIEW

**Comment by pepa65** [comment]
Is there really a need to have a different rate for zooming in vs. zooming out?? I would just use one rate, and divide using that rate when zooming out.

**Comment by pepa65** [comment]
Why go against the coding style on adding HAVE_LIBXINERAMA? The curly brackets is always on the same line as the if statement, and there is no reason to change it.
I have to say, I _love_ the idea of refactoring for the keystrokes to become OPTION_function in order to be more easily configurable!

**Comment by avlec** [comment]
> Is there really a need to have a different rate for zooming in vs. zooming out?? I would just use one rate, and divide using that rate when zooming out.

Honestly not sure, think I'm kind of on your side, but I've added support for it so it's up to what the maintainers think is too much.

**Comment by avlec** [comment]
> Why go against the coding style on adding HAVE_LIBXINERAMA?
> The curly brackets is always on the same line as the if statement, and there is no reason to change it.

Can you link the suspect lines for both points here?

**Comment by pepa65** [comment]
Sorry, don't know how to link...
```
diff --git a/src/wallpaper.c b/src/wallpaper.c
index 37b5a1d..12a47f4 100644
--- a/src/wallpaper.c
+++ b/src/wallpaper.c
@@ -504,10 +504,11 @@ void feh_wm_set_bg(char *fil, Imlib_Image im, int centered, int scaled,
 					fputc(' ', fp);
 					if (use_filelist) {
 #ifdef HAVE_LIBXINERAMA
-						for (int i = 0; (i < opt.xinerama ? num_xinerama_screens : 1) && filelist_pos; i++) {
+						for (int i = 0; (i < opt.xinerama ? num_xinerama_screens : 1) && filelist_pos; i++)
 #else
-						for (int i = 0; (i < 1                   ) && filelist_pos; i++) {
+						for (int i = 0; (i < 1                   ) && filelist_pos; i++)
 #endif
+						{
 							absolute_path = feh_absolute_path(FEH_FILE(filelist_pos->data)->filename);
 							fputs(shell_escape(absolute_path), fp);
 							filelist_pos = filelist_pos->next;
```

**Comment by pepa65** [comment]
If you require the zoom rate to be greater than 1, then you don't need to add all the disclaimers and explanation in the man page too. ;-)

**Comment by avlec** [comment]
I'm aware this is redundant. Just did this cause my error checker was losing it's mind. It doesn't really matter either way, and perhaps the change benefits it as someone reading the code might not think those are nested for loops.

**Comment by avlec** [comment]
> If you require the zoom rate to be greater than 1, then you don't need to add all the disclaimers and explanation in the man page too. ;-)

It doesn't hurt to leave people options, but I totally understand your point it was annoying to write.

**Review by derf — CHANGES_REQUESTED** [review]
Hi, thanks for the PR!

A configurable zoom rate is a sensible addition (and the switch to an options enum is also welcome). However, I do not see the benefit of having separate options for zoom-in and zoom-out. IMHO, zooming in and out should always be inverse operations, so that pressing zoom_in followed by zoom_out (or vice versa) is a no-op in most cases. For non-standard zoom steps, there's already the zoom_default, zoom_fit, and zoom_fill key bindings, which should cover 99.9% of use cases.

So I'd like you to remove --zoom-in-rate and --zoom-out-rate before I take a closer look – but so far it looks good!

**Comment by avlec** [comment]
Added the changes. And smoothed out the wording for the man/help entries.

**Review by derf — APPROVED** [review]
Yup, that looks good. I added a small sanity check to the options parser to handle ratio ≤ 1, this way we can leave out warnings in the documentation.

There's one thing I'm not quite sure about yet: "--zoom" takes a percentage as argument, but "--zoom-rate" uses a ratio. Using a percentage for --zoom-rate as well should be more consistent. What do you think?

**Comment by pepa65** [comment]
As a user I'd prefer a ratio/factor for both instead of a percentage. So like `--zoom 1.2 --zoom-rate 1.4`.

**Comment by derf** [comment]
Hmm, funny, I prefer percentage for both.

Switching from percentage to ratio for `--zoom` would be a breaking change (so it's pretty much a no-go). I'll merge the PR for now and then think about keeping the ratio for `--zoom-rate` or switching to a percentage to be consistent with `--zoom`

Anyways, thanks for the PR and for your input!

**Comment by pepa65** [comment]
Do do you prefer: `--zoom 120% --zoom-rate 140%` or `--zoom 120 --zoom-rate 140` or would both be accepted??

**Comment by derf** [comment]
The documented variant is `--zoom 120`, but `--zoom 120%` works just as well (the code stops parsing once it encounters the first non-number chaacter)

**Pull request merged**
