### PR TITLE
Fix build on FreeBSD.

### PR DESCRIPTION
**Pull request by zeising**
FreeBSD lacks the constant HOST_NAME_MAX, instead using sysconf(3) to
find out the value of the maximum host name length at run time.  Patch
to use this instead of HOST_NAME_MAX.
This brings with it the need to use malloc instead of using a statically
sized buffer for the host name, since the size of the buffer cannot be
known at run time.  Errors from sysconf or malloc just means that the
entire block of code is skipped over (the same way it's skipped if the
call to gethostname() fails), rather than returning any kind of error to
the caller or logging an error message somewhere.

### CODE REVIEW

**Comment by zeising** [comment]
I have enabled this code for all compilations. I can change it to just be done when compiling on FreeBSD, although I suspect more OSes than FreeBSD lack the hard coded value of HOST_NAME_MAX.  I'm also not 100% sure of what to do in case of error, but I took the same way out as when gethostname() failed.

**Comment by derf** [comment]
I think only doing it if HOST_NAME_MAX is not defined is the best solution. There shouldn't be much harm in always using sysconf, unless the "Some returned values may be huge; they are not suitable for allocating memory." warning in sysconf(3) also affects the hostname part on some systems.

**Comment by zeising** [comment]
That warning is not in my copy of the manual, but I guess every OS is different (obviously).  I'll see if I can work something out that works both with and without HOST_NAME_MAX.

**Comment by zeising** [comment]
Updated the patch, only use sysconf() if HOST_NAME_MAX isn't available.

**Pull request merged**
