### PR TITLE
Add --no-cycle option

### PR DESCRIPTION
**Pull request by ulteq**
Closes: #124
Closes: #191

### CODE REVIEW

**Comment by derf** [comment]
It might be better to incorporate this into --cycle-once to avoid adding even more options.

**Comment by ulteq** [comment]
> incorporate this into --cycle-once

In which way?

**Comment by ulteq** [comment]
You need to manually merge this branch before make.

**Comment by ulteq** [comment]
@derf, what do we do about this one? I know that it's not perfect to introduce yet another option, but at the same time I have no idea how to incorporate this into `--cycle-once` in a sensible way.

**Comment by derf** [comment]
Deprecating `--cycle-once` and introducing `--cycle={once,never}` sounds like the best option to me

**Comment by ulteq** [comment]
This sounds like a pretty good solution.

**Comment by derf** [comment]
There's a nasty bug in the code: If the last image of a slide show is unloadable, the check in slideshow.c:331 doesn't match and `feh_file_remove_from_list(filelist, last);` is called twice with the same value of `last`.

I'm not yet sure how to address this.

**Comment by ulteq** [comment]
> There's a nasty bug in the code

Nice catch.

> I'm not yet sure how to address this.

I think I fixed it.

**Comment by derf** [comment]
Still gives occasional Imlib2 warnings due to Imlib2 functions being called on a NULL image unfortunately. I haven't got around to properly reproduce this yet, but it seems to be related to the last few (more than one) images in a slide show being unloadable

**Comment by ulteq** [comment]
I'm pretty confident that the issue was finally fixed by moving the cycle detection to the end of the filelist walk and skipping it if unloadable files are detected. This ensures that only valid entries are stored in `current_file`: https://github.com/derf/feh/blob/8ccb194774dfa8badc2089985a918588ad0d9f4e/src/slideshow.c#L353-L358

**Comment by derf** [comment]
There's at least one issue left: `jump_last` (mapped to `End` by default) is broken when using `--on-last-slide=hold` and the last file is unloadable.

You can look into that if you like, but if it turns out to introduce lots of special code paths leaving it as-is is also fine with me. I have update the documentation accordingly.

**Comment by derf** [comment]
... actually, it's always broken no matter whether the last file is loadable or not. Which probably means it's easier to fix  at least :)

**Comment by ulteq** [comment]
`SLIDE_JUMP_BACK` and `SLIDE_JUMP_FWD` look overly complex too.

**Pull request merged**
